(define-module (personal packages genera)
  #:use-module (guix packages)
  #:use-module (guix utils)
  #:use-module (guix gexp)
  #:use-module (guix download)
  #:use-module (guix status)
  #:use-module (guix build-system trival)
  #:use-module (guix licenses))
)

